### ISSUE TITLE
Don't work on OS X

### ISSUE THREAD

**Issue by ponyspy** [Farit/TabTeleport#1]
1. Don't work on os x, any items open last tab
2. Empty tabs display ugly

Thanks

**Comment by Farit** [comment]
Hello!
Thanks for your report about bugs. I want to clarify first problem. Is it that when you select any tab to open, it is opening the same tab every time?

**Comment by ponyspy** [comment]
![tabs](https://cloud.githubusercontent.com/assets/870271/13730053/4d8bca68-e955-11e5-820b-b62ea0402edc.gif)

**Comment by Farit** [comment]
I've made a fix to how empty tabs displayed. Tomorrow I will find someone with OS X and fix that problem too.

**Comment by Farit** [comment]
Hello
Today I have looked how plugin works on OS X. Everything was ok. I tested on OS X EL Capitan 10.11.3. Sublime build was 3083. Do you still experience the same problem?
